services:
    database:
        image: mariadb:10.11
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: my_project

        ports:
            - "3307:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80" # Mappa la porta 8000 del tuo computer alla porta 80 di Nginx
        volumes:
            - ./:/var/www/html # Connette il codice del progetto a Nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Monta il file di configurazione
        depends_on:
            - php # Assicura che Nginx parta solo dopo che il servizio PHP è pronto

    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"
        depends_on:
            - database

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: none # Disattiva i log di mailhog per non intasare il terminale
        ports:
            - "1025:1025" # SMTP server
            - "8025:8025" # Web UI

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - database
        working_dir: /var/www/html
        user: "1000"

volumes:
    mariadb_data:
