services:
  # La nostra applicazione web Symfony
  - type: web
    name: symfony-app
    plan: free
    runtime: php
    buildCommand: |
      composer install --no-dev --no-interaction --optimize-autoload
      php bin/console doctrine:migrations:migrate --no-interaction
    startCommand: |
      echo "web: vendor/bin/heroku-php-apache2 public/" > Procfile
      heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString

databases:
  # Il nostro database PostgreSQL gratuito
  - name: symfony-db
    plan: free
