services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        value: postgresql://symfony_db_j4g2_user:RrcoIivnxtL2RzWzZhuyJVelox7xltV1@dpg-d3dsgdgdl3ps73c5sts0-a/symfony_db_j4g2
