services:
    # Il nostro database PostgreSQL gratuito
    - type: psql
      name: symfony-db
      plan: free

    # La nostra applicazione web Symfony
    - type: web
      name: symfony-twitter-clone
      plan: free
      # Eseguito con l'ambiente di produzione
      env: php
      # Comandi da eseguire durante la build
      buildCommand: |
          composer install --no-dev --no-interaction --optimize-autoloader
          php bin/console doctrine:migrations:migrate --no-interaction
      # Comando per avviare il server
      startCommand: vendor/bin/heroku-php-apache2 public/
      envVars:
          # Imposta l'ambiente di Symfony su 'prod'
          - key: APP_ENV
            value: prod
          # Genera una chiave segreta per la produzione
          - key: APP_SECRET
            generateValue: true
          # Collega il database all'app
          - key: DATABASE_URL
            fromService:
                type: psql
                name: symfony-db
                property: connectionString
