services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console doctrine:migrations:migrate --no-interaction --env=prod
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
databases:
  - name: symfony-db
    plan: free
    ipAllowList: [] # permette accesso a tutti
