# Exported from Render on 2025-09-30T09:30:17Z
version: "1"
services:
- type: web
  name: Symfony-App
  runtime: docker
  repo: https://github.com/MarcoCerilli/Symfony-App
  plan: free
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
