services:
  # Il nostro database PostgreSQL gratuito
  - type: postgres
    name: symfony-db
    plan: free

  # La nostra applicazione web Symfony
  - type: web
    name: symfony-twitter-clone
    plan: free
    env: php
    buildCommand: |
      composer install --no-dev --no-interaction --optimize-autoload
      php bin/console doctrine:migrations:migrate --no-interaction
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: symfony-db
          property: connectionString
